In [5]:
import numpy as np

## Реализация функции "ИЛИ" (англ. "OR") с использованием нейрона Мак-Каллока-Питтса 

In [6]:
# Задание весов и значения порога
print('Введите веса')
w1=float(input('Вес w1 ='))
w2=float(input('Вес w2 ='))
print('Введите величину порога')
theta=float(input('Порог ='))
y=np.array([0, 0, 0, 0])
x1=np.array([1, 1, 0, 0])
x2=np.array([1, 0, 1, 0])
z=np.array([1, 1, 1, 0])
con=1
while con != 0:
    zin=x1*w1+x2*w2
    for i in range(0,4):
        if zin[i]>=theta:
            y[i]=1
        else:
            y[i]=0
    print('Значение на выходе нейрона')
    print(y)
    if all(y==z):
        con=0
    else:
        print('Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
        w1=float(input('Вес w1 ='))
        w2=float(input('Вес w2 ='))
        theta=float(input('Порог ='))
print('Нейрон МакКаллока-Питса для функции "ИЛИ" (англ. "OR")')
print('Веса нейрона')
print(w1)
print(w2)
print('Пороговое значение')
print(theta)

Введите веса
Вес w1 =1
Вес w2 =1
Введите величину порога
Порог =1
Значение на выходе нейрона
[1 1 1 0]
Нейрон МакКаллока-Питса для функции "ИЛИ" (англ. "OR")
Веса нейрона
1.0
1.0
Пороговое значение
1.0


## Реализация функции "И" (англ. "AND") с использованием нейрона Мак-Каллока-Питтса 

In [7]:
# Задание весов и значения порога
print('Введите веса')
w1=float(input('Вес w1 ='))
w2=float(input('Вес w2 ='))
print('Введите величину порога')
theta=float(input('Порог ='))
y=np.array([0, 0, 0, 0])
x1=np.array([1, 1, 0, 0])
x2=np.array([1, 0, 1, 0])
z=np.array([0, 0, 0, 1])
con=1
while con != 0:
    zin=x1*w1+x2*w2
    for i in range(0,4):
        if zin[i]>=theta:
            y[i]=0
        else:
            y[i]=1
    print('Значение на выходе нейрона')
    print(y)
    if all(y==z):
        con=0
    else:
        print('Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
        w1=float(input('Вес w1 ='))
        w2=float(input('Вес w2 ='))
        theta=float(input('Порог ='))
print('Нейрон МакКаллока-Питса для функции "И" (англ. "AND")')
print('Веса нейрона')
print(w1)
print(w2)
print('Пороговое значение')
print(theta)

Введите веса
Вес w1 =1
Вес w2 =1
Введите величину порога
Порог =0.5
Значение на выходе нейрона
[0 0 0 1]
Нейрон МакКаллока-Питса для функции "И" (англ. "AND")
Веса нейрона
1.0
1.0
Пороговое значение
0.5


## Реализация функции "И" (англ. "AND") с использованием нейрона Мак-Каллока-Питтса в биполярной логике

In [8]:
# Задание весов и значения порога
print('Введите веса')
w1=float(input('Вес w1 ='))
w2=float(input('Вес w2 ='))
print('Введите величину порога')
theta=float(input('Порог ='))
y=np.array([0, 0, 0, 0])
x1=np.array([1, 1, -1, -1])
x2=np.array([1, -1, 1, -1])
z=np.array([-1, -1, -1, 1])
con=1
while con != 0:
    zin=x1*w1+x2*w2
    for i in range(0,4):
        if zin[i]>=theta:
            y[i]=-1
        else:
            y[i]=1
    print('Значение на выходе нейрона')
    print(y)
    if all(y==z):
        con=0
    else:
        print('Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
        w1=float(input('Вес w1 ='))
        w2=float(input('Вес w2 ='))
        theta=float(input('Порог ='))
print('Нейрон МакКаллока-Питса для функции "И" (англ. "AND")');
print('Веса нейрона')
print(w1)
print(w2)
print('Пороговое значение')
print(theta)

Введите веса
Вес w1 =1
Вес w2 =1
Введите величину порога
Порог =-0.5
Значение на выходе нейрона
[-1 -1 -1  1]
Нейрон МакКаллока-Питса для функции "И" (англ. "AND")
Веса нейрона
1.0
1.0
Пороговое значение
-0.5


# Реализация функции "Исключающее ИЛИ" (англ. "XOR") с помощью 2-х слойного перцептрона

In [4]:
# Задание весов и значения порога
print('Введите веса')
w_11=float(input('Вес w_11 ='))
w_12=float(input('Вес w_12 ='))
w_21=float(input('Вес w_21 ='))
w_22=float(input('Вес w_22 ='))
w11=float(input('Вес w11 ='))
w12=float(input('Вес w12 ='))

print('Введите величину порога')
theta=float(input('Порог ='))
y=np.array([0, 0, 0, 0])
y1=np.array([0, 0, 0, 0])
y2=np.array([0, 0, 0, 0])
x1=np.array([1, 1, 0, 0])
x2=np.array([1, 0, 1, 0])
z=np.array([0, 1, 1, 0])
con=1
while con != 0:
    zin1=x1*w_11+x2*w_21
    zin2=x1*w_12+x2*w_22
    for i in range(0,4):
        if zin1[i]>=theta:
            y1[i]=1
        else:
            y1[i]=0
        if zin2[i]>=theta:
            y2[i]=1
        else:
            y2[i]=0
    zin = y1*w11 + y2*w12
    for i in range(0,4):
        if zin[i]>=theta:
            y[i]=1
        else:
            y[i]=0
    print('Значение на выходе нейрона')
    print(y)
    if all(y==z):
        con=0
    else:
        print('Нейрон не обучен. Введите другие значения весовых коэффициентов и порога')
        w_11=float(input('Вес w_11 ='))
        w_12=float(input('Вес w_12 ='))
        w_21=float(input('Вес w_21 ='))
        w_22=float(input('Вес w_22 ='))
        w11=float(input('Вес w11 ='))
        w12=float(input('Вес w12 ='))
print('Нейрон МакКаллока-Питса для функции "Исключащее-ИЛИ" (англ. "XOR")');
print('Веса первого слоя');
print( [w_11, 
        w_12,
        w_21,
        w_22] )
print('Веса второго слоя');
print( [w11, 
        w12] )
print('Пороговое значение')
print(theta)

Введите веса
Вес w_11 =2
Вес w_12 =-1.5
Вес w_21 =-1.5
Вес w_22 =2
Вес w11 =2
Вес w12 =2
Введите величину порога
Порог =1
Значение на выходе нейрона
[0 1 1 0]
Нейрон МакКаллока-Питса для функции "Исключащее-ИЛИ" (англ. "XOR")
Веса первого слоя
[2.0, -1.5, -1.5, 2.0]
Веса второго слоя
[2.0, 2.0]
Пороговое значение
1.0
